#!/bin/sh

pkill sxhkd
sxhkd &
bspc rule -r "*"

# startup execs

xwallpaper --zoom media/images/bkg/blueBackground.png &
unclutter -idle 1 -jitter 30 &

w1=""
w2=""
w3=""
w4=""
w5=""
w6=""
w7=""
w8=""
w9=""

bspc monitor -d $w1 $w2 $w3 $w4 $w5 $w6 $w7 $w8 $w9

bspc config border_width         0
bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Stop Focus Stealing
bspc config ignore_ewmh_focus true
